steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld_$BRANCH_NAME', '.']
# Dummy automated test for the cointainer image
- name: ubuntu
  script: exit 0
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/helloworld_$BRANCH_NAME']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'helloworld-svc-$BRANCH_NAME', '--allow-unauthenticated', '--image', 'gcr.io/$PROJECT_ID/helloworld_$BRANCH_NAME', '--region', 'us-central1', '--port', '80']
images:
- gcr.io/$PROJECT_ID/helloworld_$BRANCH_NAME
